import type { IStorage } from "./storage";

export async function seedVendors(storage: IStorage) {
  // Seed culturally-specific Bay Area vendors for Sikh/Indian weddings
  
  const vendors = [
    // Makeup Artists
    {
      name: "Regal Beauty Studio",
      category: "makeup_artist" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Bridal makeup specialists with expertise in traditional and modern South Asian looks. Team of 5+ artists available for large wedding parties.",
      contact: "regalbeauty@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Glam by Priya",
      category: "makeup_artist" as const,
      location: "Fremont, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Affordable bridal makeup with focus on long-lasting looks for multi-day celebrations.",
      contact: "priya.makeup@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // DJs
    {
      name: "DJ Panjabi Sound",
      category: "dj" as const,
      location: "San Francisco Bay Area",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Premier Punjabi DJ service with extensive Bhangra and Bollywood music library. Available for Sangeet, Baraat, and Reception events.",
      contact: "(510) 555-0123",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Bollywood Beats DJ Services",
      category: "dj" as const,
      location: "Oakland, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Versatile DJs for all Indian wedding events with modern sound equipment.",
      contact: "bollywoodbeats@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Dhol Players
    {
      name: "Bay Area Dhol Group",
      category: "dhol_player" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Traditional dhol players available in groups of 2-5 for Baraat processions and Sangeet celebrations.",
      contact: "(408) 555-0187",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Golden State Dholis",
      category: "dhol_player" as const,
      location: "Fremont, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Professional dhol ensemble with choreographed performances. Experienced with large Baraat processions (200+ guests).",
      contact: "goldendhol@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Turban Tiers
    {
      name: "Masterful Turban Services",
      category: "turban_tier" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh"],
      description: "Expert turban tying for groom, groomsmen, and guests. Can handle 50+ turbans in 2 hours. Traditional and modern styles.",
      contact: "(408) 555-0199",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Mehndi Artists
    {
      name: "Henna Dreams by Simran",
      category: "mehndi_artist" as const,
      location: "Sunnyvale, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Award-winning mehndi artist specializing in intricate bridal designs. Hourly rates or per-hand pricing available.",
      contact: "simran.henna@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Quick Mehndi Artists",
      category: "mehndi_artist" as const,
      location: "Milpitas, CA",
      city: "San Francisco Bay Area",
      priceRange: "$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Team of 3 mehndi artists perfect for large Mehndi parties. Budget-friendly group rates.",
      contact: "quickhenna@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Photographers
    {
      name: "Eternal Moments Photography",
      category: "photographer" as const,
      location: "San Francisco Bay Area",
      city: "San Francisco Bay Area",
      priceRange: "$$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Premier wedding photography team specializing in multi-day South Asian celebrations. Cinematic style with cultural sensitivity.",
      contact: "info@eternalmoments.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Caterers
    {
      name: "Raja Sweets & Catering",
      category: "caterer" as const,
      location: "Fremont, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "High-volume Punjabi catering perfect for multi-day events. Can serve breakfast, lunch, and dinner for 100-500 guests. Specialized in Paath catering.",
      contact: "(510) 555-0156",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Taj Catering Services",
      category: "caterer" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Affordable Indian catering with vegetarian and non-vegetarian options.",
      contact: "tajcatering@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Banquet Halls
    {
      name: "Golden Peacock Banquet Hall",
      category: "banquet_hall" as const,
      location: "Milpitas, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Premier banquet hall with capacity for 400-800 guests. Full A/V setup, stage, and dance floor. Experienced with Sangeet and Reception events.",
      contact: "goldpeacock@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Gurdwaras
    {
      name: "San Jose Gurdwara Sahib",
      category: "gurdwara" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$" as const,
      culturalSpecialties: ["sikh"],
      description: "Beautiful Gurdwara with large Diwan Hall accommodating 500+ guests. Community kitchen (Langar) available. Wedding date bookings available 12 months in advance.",
      contact: "(408) 555-0211",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Decorators
    {
      name: "Marigold & Jasmine Decor",
      category: "decorator" as const,
      location: "Santa Clara, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Luxury event decoration specializing in traditional Indian weddings. Custom Mandap designs, floral arrangements, and Sangeet stage setups.",
      contact: "info@marigoldjasmine.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // Horse Rentals
    {
      name: "Royal Baraat Horses",
      category: "horse_rental" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "White horses for Baraat processions with traditional decorations. Handler included. Experienced with city street processions.",
      contact: "(408) 555-0244",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Sword Rentals
    {
      name: "Kirpan & Ceremonial Items Rental",
      category: "sword_rental" as const,
      location: "Fremont, CA",
      city: "San Francisco Bay Area",
      priceRange: "$" as const,
      culturalSpecialties: ["sikh"],
      description: "Ceremonial Kirpans and decorative swords for Sikh wedding processions. Various sizes and styles available.",
      contact: "(510) 555-0167",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Tent Services
    {
      name: "Bay Area Tent & Marquee",
      category: "tent_service" as const,
      location: "San Jose, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Large tents for home-based Paath ceremonies and outdoor events. Can accommodate 100-400 guests. Tables, chairs, and lighting included.",
      contact: "bayareatents@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Mobile Food Vendors
    {
      name: "Tandoori Truck Catering",
      category: "mobile_food" as const,
      location: "Oakland, CA",
      city: "San Francisco Bay Area",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Mobile tandoori oven perfect for casual Mehndi parties. Fresh naan, tikka, and more. Great for intimate pre-wedding events.",
      contact: "tandooritruck@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // Baraat Bands
    {
      name: "Brass Band Celebration",
      category: "baraat_band" as const,
      location: "Fremont, CA",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Traditional brass band for Baraat processions. 8-piece ensemble playing Bhangra and Bollywood hits. Street parade experienced.",
      contact: "(510) 555-0198",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
      city: "San Francisco Bay Area",
    },

    // ============================================================================
    // NEW YORK CITY VENDORS
    // ============================================================================
    {
      name: "Manhattan Mandap Designers",
      category: "mandap_decorator" as const,
      location: "Manhattan, NY",
      city: "New York City",
      priceRange: "$$$$" as const,
      culturalSpecialties: ["hindu"],
      description: "Luxury mandap design and decoration for Hindu pheras ceremony. Custom floral designs with traditional and modern aesthetics.",
      contact: "manhattanmandap@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "NYC Bridal Henna",
      category: "mehndi_artist" as const,
      location: "Jackson Heights, Queens",
      city: "New York City",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Expert mehndi artists specializing in bridal designs. Available for both intimate gatherings and large wedding parties.",
      contact: "nycmehndi@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Pandit Sharma Ji",
      category: "pandit" as const,
      location: "Edison, NJ (serves NYC area)",
      city: "New York City",
      priceRange: "$$$" as const,
      culturalSpecialties: ["hindu"],
      description: "Experienced Hindu priest for pheras, haldi, and all traditional ceremonies. Fluent in Hindi, Gujarati, and English.",
      contact: "(212) 555-0145",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Empire State Caterers",
      category: "caterer" as const,
      location: "Brooklyn, NY",
      city: "New York City",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi", "hindu"],
      description: "Full-service South Asian catering for 50-1000+ guests. Authentic Punjabi, North Indian, and South Indian menus. Halal options available.",
      contact: "empirestatecatering@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "NYC Bollywood DJs",
      category: "dj" as const,
      location: "Manhattan, NY",
      city: "New York City",
      priceRange: "$$$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Premier DJ service for Sangeet and Reception. Extensive Bollywood, Bhangra, and Western music library. Top-tier sound and lighting.",
      contact: "(646) 555-0199",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Queens Dhol Beats",
      category: "dhol_player" as const,
      location: "Queens, NY",
      city: "New York City",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Traditional dhol players for Baraat processions. Available in groups of 2-6. Street parade experienced in NYC.",
      contact: "(718) 555-0156",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // ============================================================================
    // LOS ANGELES VENDORS
    // ============================================================================
    {
      name: "LA Bridal Glam Studio",
      category: "makeup_artist" as const,
      location: "Artesia, CA",
      city: "Los Angeles",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Celebrity makeup artists specializing in South Asian bridal looks. Available for multi-day wedding events.",
      contact: "labridalglam@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Hollywood Haldi Supplies",
      category: "haldi_supplies" as const,
      location: "Cerritos, CA",
      city: "Los Angeles",
      priceRange: "$" as const,
      culturalSpecialties: ["hindu"],
      description: "Complete haldi ceremony supply packages including turmeric paste, decorative trays, and seating arrangements.",
      contact: "hollywoodhaldi@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "SoCal Sangeet Sounds",
      category: "dj" as const,
      location: "Los Angeles, CA",
      city: "Los Angeles",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Affordable DJ services for all wedding events. Bilingual MCs available in Hindi, Punjabi, and English.",
      contact: "(310) 555-0187",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "LA Temple Catering",
      category: "caterer" as const,
      location: "Norwalk, CA",
      city: "Los Angeles",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Vegetarian and vegan South Asian catering. Perfect for Gurdwara and temple ceremonies. Langar-style service available.",
      contact: "latemplecatering@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Vedic Astrologer Gupta",
      category: "astrologer" as const,
      location: "Anaheim, CA",
      city: "Los Angeles",
      priceRange: "$$" as const,
      culturalSpecialties: ["hindu"],
      description: "Traditional Vedic astrologer for mahurat (auspicious timing) and kundali matching. Consultation in Hindi and English.",
      contact: "(714) 555-0123",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Artesia Mehndi Artists",
      category: "mehndi_artist" as const,
      location: "Artesia, CA",
      city: "Los Angeles",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Award-winning mehndi artists with intricate bridal designs. Can handle parties of 50+ guests.",
      contact: "artesiamehndi@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },

    // ============================================================================
    // CHICAGO VENDORS
    // ============================================================================
    {
      name: "Chicago Shaadi Planners",
      category: "decorator" as const,
      location: "Schaumburg, IL",
      city: "Chicago",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Full-service decoration for all wedding events. Mandap, stage, and venue decoration. Floral and fabric specialists.",
      contact: "chicagoshaadi@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Windy City Dhol",
      category: "dhol_player" as const,
      location: "Naperville, IL",
      city: "Chicago",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Professional dhol players for Baraat and Sangeet. Winter weather experienced for outdoor processions.",
      contact: "(630) 555-0145",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Midwest Indian Catering",
      category: "caterer" as const,
      location: "Chicago, IL",
      city: "Chicago",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "punjabi"],
      description: "Affordable catering for 100-500 guests. Punjabi, Gujarati, and South Indian menus available.",
      contact: "midwestcatering@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Chicago Bridal Beauty",
      category: "makeup_artist" as const,
      location: "Schaumburg, IL",
      city: "Chicago",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Bridal makeup and hair styling for South Asian weddings. Airbrush specialists for long-lasting looks.",
      contact: "(847) 555-0198",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Garland Garden Chicago",
      category: "garland_maker" as const,
      location: "Oak Brook, IL",
      city: "Chicago",
      priceRange: "$$$" as const,
      culturalSpecialties: ["hindu", "sikh"],
      description: "Fresh floral garlands (jaimala/varmala) for wedding ceremonies. Rose, marigold, and custom designs available.",
      contact: "garlandgarden@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },

    // ============================================================================
    // SEATTLE VENDORS
    // ============================================================================
    {
      name: "Pacific Northwest Punjabi Catering",
      category: "caterer" as const,
      location: "Bellevue, WA",
      city: "Seattle",
      priceRange: "$$$" as const,
      culturalSpecialties: ["sikh", "punjabi"],
      description: "Premium Punjabi catering using locally-sourced ingredients. Full bar service available. Serves 50-800 guests.",
      contact: "pnwpunjabi@example.com",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Seattle Sangeet DJs",
      category: "dj" as const,
      location: "Seattle, WA",
      city: "Seattle",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu", "general"],
      description: "Experienced DJs for Sangeet and Reception events. Bhangra, Bollywood, and Top 40 mixes. Professional lighting.",
      contact: "(206) 555-0176",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Emerald City Mehndi",
      category: "mehndi_artist" as const,
      location: "Redmond, WA",
      city: "Seattle",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh", "hindu"],
      description: "Professional mehndi artists for bridal and guest henna. Organic, natural henna paste. Available for home parties.",
      contact: "emeraldmehndi@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Pandit Kapoor Services",
      category: "pandit" as const,
      location: "Bellevue, WA",
      city: "Seattle",
      priceRange: "$$" as const,
      culturalSpecialties: ["hindu"],
      description: "Hindu priest for all wedding ceremonies. Specializes in North Indian rituals. Fluent in Hindi, Punjabi, and English.",
      contact: "(425) 555-0134",
      rating: null,
      reviewCount: 0,
      featured: true,
      portfolio: null,
      availability: null,
    },
    {
      name: "Seattle Pooja Essentials",
      category: "pooja_items" as const,
      location: "Bellevue, WA",
      city: "Seattle",
      priceRange: "$" as const,
      culturalSpecialties: ["hindu"],
      description: "Complete pooja item packages for Hindu ceremonies. Thali sets, diyas, incense, and all ceremonial essentials.",
      contact: "seattlepooja@example.com",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
    {
      name: "Rainier Turban Services",
      category: "turban_tier" as const,
      location: "Kent, WA",
      city: "Seattle",
      priceRange: "$$" as const,
      culturalSpecialties: ["sikh"],
      description: "Expert turban tying for groom and guests. Can handle 30+ turbans per hour. Traditional Punjabi styles.",
      contact: "(253) 555-0187",
      rating: null,
      reviewCount: 0,
      featured: false,
      portfolio: null,
      availability: null,
    },
  ];

  for (const vendor of vendors) {
    await storage.createVendor(vendor);
  }

  console.log(`Seeded ${vendors.length} vendors across 5 US cities`);
}

